name: Magdalena Osak
title: Docs about the docs.  
description:  This is my final project.
remote_theme: madzka/docs-about-the-docs

color_scheme: light



aux_links:
  "Source repository on GitHub":
    - "//github.com/madzka.github.io/docs-about-the-dosc.io"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is my final project"